
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class CustomerCheckin extends javax.swing.JFrame {

         Connection con=null;
         Statement st=null;
         PreparedStatement pst=null;
         ResultSet rs=null;
         
    public CustomerCheckin() {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("yyyy/MM/dd");
        Date date=new Date();
        txtdate.setText(obj.format(date));
        
        try {
                 Class.forName("com.mysql.jdbc.Driver");
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "");
             } catch (ClassNotFoundException | SQLException ex) {
                 Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
             }
        khairul();
    }
    
    public void khairul(){
             try {
                 pst=con.prepareStatement("Select roomnumber from room where bed=? and roomtype=? and status=?");
                 pst.setString(1, combobed.getItemAt(combobed.getSelectedIndex()));
                 pst.setString(2, comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
                 pst.setString(3, "NOT-BOOKED");
                 rs=pst.executeQuery();
                 comboroomnumber.removeAllItems();
                 while(rs.next()){
                        comboroomnumber.addItem(rs.getString("roomnumber"));
                 }
                 pst=con.prepareStatement("select price from room where roomnumber=?");
                 pst.setString(1, comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
                 rs=pst.executeQuery();
                 if(rs.next()){
                     txtprice.setText(rs.getString("price"));
                 
                 }
                 
             } catch (SQLException ex) {
                 Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
             }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combogender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combobed = new javax.swing.JComboBox<>();
        comboroomtype = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btncheckin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboroomnumber = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 11, 21, 22));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer Registration & Check IN.png"))); // NOI18N
        jLabel1.setText("Customer Checkin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 120, 116, 20));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 151, 177, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 211, -1, -1));

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 241, 177, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 305, 177, -1));

        combogender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Famale", "Male" }));
        getContentPane().add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 342, 177, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Nationnality");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 423, -1, -1));

        txtnat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnatActionPerformed(evt);
            }
        });
        getContentPane().add(txtnat, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 453, 177, 33));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("NID Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 519, -1, -1));

        txtnid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtnid, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 550, 177, 34));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Check In Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 121, 144, -1));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 151, 179, 32));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Bed Type");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 211, 179, -1));

        combobed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        combobed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobedItemStateChanged(evt);
            }
        });
        getContentPane().add(combobed, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 241, 179, 29));

        comboroomtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC" }));
        comboroomtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboroomtypeItemStateChanged(evt);
            }
        });
        comboroomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboroomtypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("Price");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 179, -1));

        txtprice.setEditable(false);
        txtprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 179, 34));

        btncheckin.setBackground(new java.awt.Color(204, 0, 0));
        btncheckin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncheckin.setText("Check In Now");
        btncheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, -1, 40));

        btnclear.setBackground(new java.awt.Color(153, 0, 0));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, -1, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 179, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setText("Room Number");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        comboroomnumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(comboroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 170, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1080, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnatActionPerformed

    private void comboroomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboroomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboroomtypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                   dispose();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combobedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobedItemStateChanged
       khairul();
    }//GEN-LAST:event_combobedItemStateChanged

    private void comboroomtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboroomtypeItemStateChanged
      khairul();
    }//GEN-LAST:event_comboroomtypeItemStateChanged

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtname.setText("");
        txtnid.setText("");
        txtmobile.setText("");
        txtnat.setText("");
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void btncheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinActionPerformed
       if(txtname.getText().equals("")){
       txtname.requestFocus();
        JOptionPane.showMessageDialog(this, "All filed is requried");
    } 
       else if(txtmobile.getText().equals("")){
       txtmobile.requestFocus();
        JOptionPane.showMessageDialog(this, "All filed is requried");
    }//GEN-LAST:event_btncheckinActionPerformed
      else if(txtnid.getText().equals("")){
       txtname.requestFocus();
        JOptionPane.showMessageDialog(this, "All filed is requried");
    }                                          
      else if(txtnat.getText().equals("")){
       txtnat.requestFocus();
        JOptionPane.showMessageDialog(this, "All filed is requried");
    } 
      else{
      
           try {
               pst=con.prepareStatement("insert into customer(name,mobile,gender,id,nationality,date,roomnumber,bed,roomtype,price,status)values(?,?,?,?,?,?,?,?,?,?,?)");
               pst.setString(1, txtname.getText());
               pst.setString(2,txtmobile.getText());
               pst.setString(3,combogender.getItemAt(combogender.getSelectedIndex()));
               pst.setString(4, txtnid.getText());
               pst.setString(5, txtnat.getText());
               pst.setString(6, txtdate.getText());
               pst.setString(7, comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
               pst.setString(8,combobed.getItemAt(combobed.getSelectedIndex()));
               pst.setString(9,comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
               pst.setString(10, txtprice.getText());
               pst.setString(11, "NULL"); 
               pst.executeUpdate(); 
               JOptionPane.showMessageDialog(this, "Customer Checked in Successfully");
               txtname.setText("");
               txtnid.setText("");
               txtmobile.setText("");
               txtnat.setText("");
               pst=con.prepareStatement("update room set status=? where roomnumber=?");
            pst.setString(1,"BOOKED" );
            pst.setString(2, (String) comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
            pst.executeUpdate();       
            khairul();
           } catch (SQLException ex) {
               Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
           }
      
      }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckin;
    private javax.swing.JButton btnclear;
    private javax.swing.JComboBox<String> combobed;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JComboBox<String> comboroomnumber;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnat;
    private javax.swing.JTextField txtnid;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
